[package]
name = "{{project-name}}"
description = "{{description}}"
version = "0.1.0"
edition = "2021"

[dependencies]
hmt-detection = { git = "https://github.com/hummanta/hummanta.git", tag = "v0.11.4"}
